[project]
id = "gdhistogram"
name = "GDHistogram"

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn gdhistogram.web_app:app --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
